// Mocks generated by Mockito 5.0.10 from annotations
// in riverpod_machine/test/riverpod_machine_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import 'riverpod_machine_test.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [EventListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventListener<Event> extends _i1.Mock
    implements _i2.EventListener<Event> {
  MockEventListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(_i2.Event1? event) =>
      super.noSuchMethod(Invocation.method(#call, [event]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [OnExitCb].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnExitCb extends _i1.Mock implements _i2.OnExitCb {
  MockOnExitCb() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call() => super.noSuchMethod(Invocation.method(#call, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
