name: riverpod_machine
description: Finite State Machine build on top of riverpod.
version: 0.0.1-dev.1
homepage: https://github.com/smiLLe/riverpod_machine

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^1.0.0-dev.1
  freezed_annotation: 0.14.2
  collection: ^1.15.0 

dev_dependencies:
  build_runner:
  freezed: 0.14.2
  test: ^1.17.9
  mockito: ^5.0.10
  flutter_lints: ^1.0.3
